In [1]:
import pandas as pd
GB=pd.read_csv('C:/Users/SAMSUNG/Desktop/GBvideos.csv')
US=pd.read_csv('C:/Users/SAMSUNG/Desktop/USvideos.csv')

In [2]:
GB.head()  #영국데이터 이용

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [3]:
#category_id별 likes 평균 구하기
avg_likes_by_category_id=GB.groupby('category_id').likes.mean()
print(avg_likes_by_category_id)

category_id
1      57205.523089
2      24608.506944
10    272138.508943
15     28629.913858
17     39270.313057
19      9674.447917
20     39220.127517
22     46273.495899
23     78431.168490
24     81572.362012
25     25021.685714
26     26639.183091
27     38440.687090
28     61531.127413
29    271695.733333
43     41836.900000
Name: likes, dtype: float64

In [4]:
#category id별 likes 최대값 구하기
max_likes_by_category_id=GB.groupby('category_id').likes.max()
print(max_likes_by_category_id)

category_id
1      461135
2      114841
10    5613827
15     187524
17    1291139
19      23791
20    1031695
22     625174
23    1253154
24    3312868
25     610526
26     341145
27     383049
28     392249
29    2061275
43      44588
Name: likes, dtype: int64

In [5]:
#category id별 likes 최소값 구하기
min_likes_by_category_id=GB.groupby('category_id').likes.min()
print(min_likes_by_category_id)

category_id
1         0
2        61
10        0
15      147
17        0
19       54
20        0
22        0
23       22
24        0
25       12
26        5
27       94
28        0
29      708
43    34615
Name: likes, dtype: int64

In [6]:
#category_id별 comment_count 평균 구하기
avg_comment_count_by_category_id=GB.groupby('category_id').comment_count.mean()
print(avg_comment_count_by_category_id)

category_id
1      6049.674428
2      3507.534722
10    21303.849062
15     2630.520599
17     5273.322496
19     1231.010417
20     3449.101790
22     6395.471292
23     9145.960613
24    12812.082420
25     7662.533878
26     3815.506224
27     3581.844639
28     7778.117761
29    85253.222222
43     4047.850000
Name: comment_count, dtype: float64

In [7]:
#category_id별 comment_count 최대값 구하기
max_comment_count_by_category_id=GB.groupby('category_id').comment_count.max()
print(max_comment_count_by_category_id)

category_id
1       50255
2       12083
10    1228655
15      18532
17      91663
19       2716
20      31803
22     154958
23     205692
24    1626501
25      86221
26     139582
27      19451
28      53786
29     704824
43       4335
Name: comment_count, dtype: int64

In [8]:
#category_id별 comment_count 최소값 구하기
min_comment_count_by_category_id=GB.groupby('category_id').comment_count.min()
print(min_comment_count_by_category_id)

category_id
1        0
2        0
10       0
15      23
17       0
19       7
20       0
22       0
23       4
24       0
25       0
26       9
27       0
28       0
29      95
43    3448
Name: comment_count, dtype: int64

In [9]:
US.head()  #미국데이터 이용

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [10]:
#category_id별 likes 평균 구하기
avg_likes_by_category_id=US.groupby('category_id').likes.mean()
print(avg_likes_by_category_id)

category_id
1      70787.836247
2      11056.395833
10    218918.199011
15     21055.110870
17     45363.942502
19     12030.462687
20     84502.183599
22     58135.825234
23     62582.223315
24     53243.325070
25      7298.364696
26     39286.076942
27     29745.031401
28     34374.276551
29    259923.614035
43     18993.666667
Name: likes, dtype: float64

In [11]:
#category id별 likes 최대값 구하기
max_likes_by_category_id=US.groupby('category_id').likes.max()
print(max_likes_by_category_id)

category_id
1      922355
2       97030
10    5613827
15     178243
17    1121217
19      42447
20     444203
22    2032463
23     865679
24    3093544
25     163338
26     605954
27     240989
28     564804
29    1988746
43      33261
Name: likes, dtype: int64

In [12]:
#category id별 likes 최소값 구하기
min_likes_by_category_id=US.groupby('category_id').likes.min()
print(min_likes_by_category_id)

category_id
1       0
2       0
10      0
15      6
17      0
19      3
20      2
22      0
23      6
24      0
25      0
26      0
27      0
28      0
29      0
43    810
Name: likes, dtype: int64

In [27]:
#category_id별 comment_count 평균 구하기
avg_comment_count_by_category_id=df2.groupby('category_id').comment_count.mean()
print(avg_comment_count_by_category_id)

category_id
1      7627.744136
2      2042.830729
10    19359.764524
15     2892.070652
17     5148.185373
19     2267.440299
20    18042.488372
22     7719.013084
23     6521.718831
24     7383.229426
25     2428.400885
26     5583.586589
27     3286.378019
28     4993.721783
29    84364.859649
43     1668.719298
Name: comment_count, dtype: float64

In [28]:
#category_id별 comment_count 최대값 구하기
max_comment_count_by_category_id=df1.groupby('category_id').comment_count.max()
print(max_comment_count_by_category_id)

category_id
1       50255
2       12083
10    1228655
15      18532
17      91663
19       2716
20      31803
22     154958
23     205692
24    1626501
25      86221
26     139582
27      19451
28      53786
29     704824
43       4335
Name: comment_count, dtype: int64

In [29]:
#category_id별 comment_count 최소값 구하기
min_comment_count_by_category_id=df1.groupby('category_id').comment_count.min()
print(min_comment_count_by_category_id)

category_id
1        0
2        0
10       0
15      23
17       0
19       7
20       0
22       0
23       4
24       0
25       0
26       9
27       0
28       0
29      95
43    3448
Name: comment_count, dtype: int64